repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-xml
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.17.0
    hooks:
    -   id: eslint

-   repo: https://github.com/digitalpulp/pre-commit-php
    rev: 1.4.0
    hooks:
    -   id: php-cs
        files: \.(php)$
