<?php

namespace App\Models\Enums\Territory;

use App\Models\Traits\EnumToArray;

enum Country: string
{
    use EnumToArray;

    case AFGHANISTAN = '2001';
    case ALAND_ISLANDS = '3002';
    case ALBANIA = '3003';
    case ALGERIA = '1004';
    case AMERICAN_SAMOA = '605';
    case ANDORRA = '3006';
    case ANGOLA = '1007';
    case ANGUILLA = '4008';
    case ANTIGUA_AND_BARBUDA = '4010';
    case ARGENTINA = '5011';
    case ARMENIA = '2012';
    case ARUBA = '4013';
    case AUSTRALIA = '6014';
    case AUSTRIA = '3015';
    case AZERBAIJAN = '2016';
    case BAHAMAS_THE = '4017';
    case BAHRAIN = '2018';
    case BANGLADESH = '2019';
    case BARBADOS = '4020';
    case BELARUS = '3021';
    case BELGIUM = '3022';
    case BELIZE = '4023';
    case BENIN = '1024';
    case BERMUDA = '4025';
    case BHUTAN = '2026';
    case BOLIVIA_PLURINATIONAL_STATE_OF = '5027';
    case BONAIRE_SINT_EUSTATIUS_AND_SABA = '4028';
    case BOSNIA_AND_HERZEGOVINA = '3029';
    case BOTSWANA = '1030';
    case BOUVET_ISLAND = '5031';
    case BRAZIL = '5032';
    case BRITISH_INDIAN_OCEAN_TERRITORY_THE = '2033';
    case BRUNEI_DARUSSALAM = '2034';
    case BULGARIA = '3035';
    case BURKINA_FASO = '1036';
    case BURUNDI = '1037';
    case CABO_VERDE = '1038';
    case CAMBODIA = '2039';
    case CAMEROON = '1040';
    case CANADA = '4041';
    case CAYMAN_ISLANDS_THE = '4042';
    case CENTRAL_AFRICAN_REPUBLIC_THE = '1043';
    case CHAD = '1044';
    case CHILE = '5045';
    case CHINA = '2046';
    case CHRISTMAS_ISLAND = '6047';
    case COCOS_KEELING_ISLANDS_THE = '6048';
    case COLOMBIA = '5049';
    case COMOROS_THE = '1050';
    case CONGO_THE = '1051';
    case CONGO_THE_DEMOCRATIC_REPUBLIC_OF_THE = '1052';
    case COOK_ISLANDS_THE = '6053';
    case COSTA_RICA = '4054';
    case COTE_D_IVOIRE = '1055';
    case CROATIA = '3056';
    case CUBA = '4057';
    case CURACAO = '4058';
    case CYPRUS = '3059';
    case CZECHIA = '3060';
    case DENMARK = '3061';
    case DJIBOUTI = '1062';
    case DOMINICA = '4063';
    case DOMINICAN_REPUBLIC_THE = '4064';
    case ECUADOR = '5065';
    case EGYPT = '1066';
    case EL_SALVADOR = '4067';
    case EQUATORIAL_GUINEA = '1068';
    case ERITREA = '1069';
    case ESTONIA = '3070';
    case ESWATINI = '1071';
    case ETHIOPIA = '1072';
    case FALKLAND_ISLANDS_THE_MALVINAS = '5073';
    case FAROE_ISLANDS_THE = '3074';
    case FIJI = '6075';
    case FINLAND = '3076';
    case FRANCE = '3077';
    case FRENCH_GUIANA = '5078';
    case FRENCH_POLYNESIA = '6079';
    case FRENCH_SOUTHERN_TERRITORIES_THE = '1080';
    case GABON = '1081';
    case GAMBIA_THE = '1082';
    case GEORGIA = '2083';
    case GERMANY = '3084';
    case GHANA = '1085';
    case GIBRALTAR = '3086';
    case GREECE = '3087';
    case GREENLAND = '4088';
    case GRENADA = '4089';
    case GUADELOUPE = '4090';
    case GUAM = '6091';
    case GUATEMALA = '4092';
    case GUERNSEY = '3093';
    case GUINEA = '094';
    case GUINEA_BISSAU = '1095';
    case GUYANA = '5096';
    case HAITI = '4097';
    case HEARD_ISLAND_AND_MCDONALD_ISLANDS = '6098';
    case HOLY_SEE_THE = '3099';
    case HONDURAS = '4100';
    case HONG_KONG = '2101';
    case HUNGARY = '3102';
    case ICELAND = '3103';
    case INDIA = '2104';
    case INDONESIA = '2105';
    case IRAN_ISLAMIC_REPUBLIC_OF = '2106';
    case IRAQ = '2107';
    case IRELAND = '3108';
    case ISLE_OF_MAN = '3109';
    case ISRAEL = '2110';
    case ITALY = '3111';
    case JAMAICA = '4112';
    case JAPAN = '2113';
    case JERSEY = '3114';
    case JORDAN = '2115';
    case KAZAKHSTAN = '2116';
    case KENYA = '1117';
    case KIRIBATI = '6118';
    case KOREA_THE_DEMOCRATIC_PEOPLE_S_REPUBLIC_OF = '2119';
    case KOREA_THE_REPUBLIC_OF = '2120';
    case KUWAIT = '2121';
    case KYRGYZSTAN = '2122';
    case LAO_PEOPLE_S_DEMOCRATIC_REPUBLIC_THE = '2123';
    case LATVIA = '3124';
    case LEBANON = '2125';
    case LESOTHO = '1126';
    case LIBERIA = '1127';
    case LIBYA = '1128';
    case LIECHTENSTEIN = '3129';
    case LITHUANIA = '3130';
    case LUXEMBOURG = '3131';
    case MACAO = '2132';
    case MADAGASCAR = '1133';
    case MALAWI = '1134';
    case MALAYSIA = '2135';
    case MALDIVES = '2136';
    case MALI = '1137';
    case MALTA = '3138';
    case MARSHALL_ISLANDS_THE = '6139';
    case MARTINIQUE = '4140';
    case MAURITANIA = '1141';
    case MAURITIUS = '1142';
    case MAYOTTE = '1143';
    case MEXICO = '4144';
    case MICRONESIA_FEDERATED_STATES_OF = '6145';
    case MOLDOVA_THE_REPUBLIC_OF = '3146';
    case MONACO = '3147';
    case MONGOLIA = '2148';
    case MONTENEGRO = '3149';
    case MONTSERRAT = '44150';
    case MOROCCO = '1151';
    case MOZAMBIQUE = '1152';
    case MYANMAR = '2153';
    case NAMIBIA = '1154';
    case NAURU = '6155';
    case NEPAL = '2156';
    case NETHERLANDS_THE = '3157';
    case NEW_CALEDONIA = '6158';
    case NEW_ZEALAND = '6159';
    case NICARAGUA = '4160';
    case NIGER_THE = '1161';
    case NIGERIA = '1162';
    case NIUE = '6163';
    case NORFOLK_ISLAND = '6164';
    case NORTH_MACEDONIA = '3165';
    case NORTHERN_MARIANA_ISLANDS_THE = '6166';
    case NORWAY = '3167';
    case OMAN = '2168';
    case PAKISTAN = '2169';
    case PALAU = '6170';
    case PALESTINE_STATE_OF = '2171';
    case PANAMA = '4172';
    case PAPUA_NEW_GUINEA = '6173';
    case PARAGUAY = '5174';
    case PERU = '5175';
    case PHILIPPINES_THE = '2176';
    case PITCAIRN = '6177';
    case POLAND = '3178';
    case PORTUGAL = '3179';
    case PUERTO_RICO = '4180';
    case QATAR = '2181';
    case REUNION = '1182';
    case ROMANIA = '3183';
    case RUSSIAN_FEDERATION_THE = '3184';
    case RWANDA = '1185';
    case SAINT_BARTHELEMY = '4186';
    case SAINT_HELENA_ASCENSION_AND_TRISTAN_DA_CUNHA = '4187';
    case SAINT_KITTS_AND_NEVIS = '4188';
    case SAINT_LUCIA = '4189';
    case SAINT_MARTIN_FRENCH_PART = '4190';
    case SAINT_PIERRE_AND_MIQUELON = '4191';
    case SAINT_VINCENT_AND_THE_GRENADINES = '4192';
    case SAMOA = '6193';
    case SAN_MARINO = '3194';
    case SAO_TOME_AND_PRINCIPE = '1195';
    case SAUDI_ARABIA = '2196';
    case SENEGAL = '1197';
    case SERBIA = '3198';
    case SEYCHELLES = '1199';
    case SIERRA_LEONE = '1200';
    case SINGAPORE = '2201';
    case SINT_MAARTEN_DUTCH_PART = '4202';
    case SLOVAKIA = '3203';
    case SLOVENIA = '3204';
    case SOLOMON_ISLANDS = '6205';
    case SOMALIA = '1206';
    case SOUTH_AFRICA = '1207';
    case SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS = '5208';
    case SOUTH_SUDAN = '1209';
    case SPAIN = '3210';
    case SRI_LANKA = '2211';
    case SUDAN_THE = '1212';
    case SURINAME = '5213';
    case SVALBARD_AND_JAN_MAYEN = '3214';
    case SWEDEN = '3215';
    case SWITZERLAND = '3216';
    case SYRIAN_ARAB_REPUBLIC_THE = '2217';
    case TAIWAN_PROVINCE_OF_CHINA = '2218';
    case TAJIKISTAN = '2219';
    case TANZANIA_THE_UNITED_REPUBLIC_OF = '1220';
    case THAILAND = '2221';
    case TIMOR_LESTE = '2222';
    case TOGO = '1223';
    case TOKELAU = '6224';
    case TONGA = '6225';
    case TRINIDAD_AND_TOBAGO = '4226';
    case TUNISIA = '1227';
    case TURKEY = '2228';
    case TURKMENISTAN = '2229';
    case TURKS_AND_CAICOS_ISLANDS_THE = '4230';
    case TUVALU = '6231';
    case UGANDA = '1232';
    case UKRAINE = '3233';
    case UNITED_ARAB_EMIRATES_THE = '2234';
    case UNITED_KINGDOM_OF_GREAT_BRITAIN_AND_NORTHERN_IRELAND_THE = '3235';
    case UNITED_STATES_MINOR_OUTLYING_ISLANDS_THE = '4236';
    case UNITED_STATES_OF_AMERICA_THE = '4237';
    case URUGUAY = '5238';
    case UZBEKISTAN = '2239';
    case VANUATU = '6240';
    case VENEZUELA_BOLIVARIAN_REPUBLIC_OF = '5241';
    case VIET_NAM = '2242';
    case VIRGIN_ISLANDS_BRITISH = '4243';
    case VIRGIN_ISLANDS_U_S = '4244';
    case WALLIS_AND_FUTUNA = '6245';
    case WESTERN_SAHARA = '1246';
    case YEMEN = '2247';
    case ZAMBIA = '1248';
    case ZIMBABWE = '1249';

    public function name(): string
    {
        return match ($this) {
            Country::AFGHANISTAN => __('AFGHANISTAN'),
            Country::ALAND_ISLANDS => __('ALAND_ISLANDS'),
            Country::ALBANIA => __('ALBANIA'),
            Country::ALGERIA => __('ALGERIA'),
            Country::AMERICAN_SAMOA => __('AMERICAN_SAMOA'),
            Country::ANDORRA => __('ANDORRA'),
            Country::ANGOLA => __('ANGOLA'),
            Country::ANGUILLA => __('ANGUILLA'),
            Country::ANTIGUA_AND_BARBUDA => __('ANTIGUA_AND_BARBUDA'),
            Country::ARGENTINA => __('ARGENTINA'),
            Country::ARMENIA => __('ARMENIA'),
            Country::ARUBA => __('ARUBA'),
            Country::AUSTRALIA => __('AUSTRALIA'),
            Country::AUSTRIA => __('AUSTRIA'),
            Country::AZERBAIJAN => __('AZERBAIJAN'),
            Country::BAHAMAS_THE => __('BAHAMAS'),
            Country::BAHRAIN => __('BAHRAIN'),
            Country::BANGLADESH => __('BANGLADESH'),
            Country::BARBADOS => __('BARBADOS'),
            Country::BELARUS => __('BELARUS'),
            Country::BELGIUM => __('BELGIUM'),
            Country::BELIZE => __('BELIZE'),
            Country::BENIN => __('BENIN'),
            Country::BERMUDA => __('BERMUDA'),
            Country::BHUTAN => __('BHUTAN'),
            Country::BOLIVIA_PLURINATIONAL_STATE_OF => __('BOLIVIA_PLURINATIONAL_STATE_OF'),
            Country::BONAIRE_SINT_EUSTATIUS_AND_SABA => __('BONAIRE_SINT_EUSTATIUS_AND_SABA'),
            Country::BOSNIA_AND_HERZEGOVINA => __('BOSNIA_AND_HERZEGOVINA'),
            Country::BOTSWANA => __('BOTSWANA'),
            Country::BOUVET_ISLAND => __('BOUVET_ISLAND'),
            Country::BRAZIL => __('BRAZIL'),
            Country::BRITISH_INDIAN_OCEAN_TERRITORY_THE => __('BRITISH_INDIAN_OCEAN_TERRITORY_THE'),
            Country::BRUNEI_DARUSSALAM => __('BRUNEI_DARUSSALAM'),
            Country::BULGARIA => __('BULGARIA'),
            Country::BURKINA_FASO => __('BURKINA_FASO'),
            Country::BURUNDI => __('BURUNDI'),
            Country::CABO_VERDE => __('CABO_VERDE'),
            Country::CAMBODIA => __('CAMBODIA'),
            Country::CAMEROON => __('CAMEROON'),
            Country::CANADA => __('CANADA'),
            Country::CAYMAN_ISLANDS_THE => __('CAYMAN_ISLANDS_THE'),
            Country::CENTRAL_AFRICAN_REPUBLIC_THE => __('CENTRAL_AFRICAN_REPUBLIC_THE'),
            Country::CHAD => __('CHAD'),
            Country::CHILE => __('CHILE'),
            Country::CHINA => __('CHINA'),
            Country::CHRISTMAS_ISLAND => __('CHRISTMAS_ISLAND'),
            Country::COCOS_KEELING_ISLANDS_THE => __('COCOS_KEELING_ISLANDS_THE'),
            Country::COLOMBIA => __('COLOMBIA'),
            Country::COMOROS_THE => __('COMOROS_THE'),
            Country::CONGO_THE => __('CONGO_THE'),
            Country::CONGO_THE_DEMOCRATIC_REPUBLIC_OF_THE => __('CONGO_THE_DEMOCRATIC_REPUBLIC_OF_THE'),
            Country::COOK_ISLANDS_THE => __('COOK_ISLANDS_THE'),
            Country::COSTA_RICA => __('COSTA_RICA'),
            Country::COTE_D_IVOIRE => __('COTE_D_IVOIRE'),
            Country::CROATIA => __('CROATIA'),
            Country::CUBA => __('CUBA'),
            Country::CURACAO => __('CURACAO'),
            Country::CYPRUS => __('CYPRUS'),
            Country::CZECHIA => __('CZECHIA'),
            Country::DENMARK => __('DENMARK'),
            Country::DJIBOUTI => __('DJIBOUTI'),
            Country::DOMINICA => __('DOMINICA'),
            Country::DOMINICAN_REPUBLIC_THE => __('DOMINICAN_REPUBLIC_THE'),
            Country::ECUADOR => __('ECUADOR'),
            Country::EGYPT => __('EGYPT'),
            Country::EL_SALVADOR => __('EL_SALVADOR'),
            Country::EQUATORIAL_GUINEA => __('EQUATORIAL_GUINEA'),
            Country::ERITREA => __('ERITREA'),
            Country::ESTONIA => __('ESTONIA'),
            Country::ESWATINI => __('ESWATINI'),
            Country::ETHIOPIA => __('ETHIOPIA'),
            Country::FALKLAND_ISLANDS_THE_MALVINAS => __('FALKLAND_ISLANDS_THE_MALVINAS'),
            Country::FAROE_ISLANDS_THE => __('FAROE_ISLANDS_THE'),
            Country::FIJI => __('FIJI'),
            Country::FINLAND => __('FINLAND'),
            Country::FRANCE => __('FRANCE'),
            Country::FRENCH_GUIANA => __('FRENCH_GUIANA'),
            Country::FRENCH_POLYNESIA => __('FRENCH_POLYNESIA'),
            Country::FRENCH_SOUTHERN_TERRITORIES_THE => __('FRENCH_SOUTHERN_TERRITORIES_THE'),
            Country::GABON => __('GABON'),
            Country::GAMBIA_THE => __('GAMBIA_THE'),
            Country::GEORGIA => __('GEORGIA'),
            Country::GERMANY => __('GERMANY'),
            Country::GHANA => __('GHANA'),
            Country::GIBRALTAR => __('GIBRALTAR'),
            Country::GREECE => __('GREECE'),
            Country::GREENLAND => __('GREENLAND'),
            Country::GRENADA => __('GRENADA'),
            Country::GUADELOUPE => __('GUADELOUPE'),
            Country::GUAM => __('GUAM'),
            Country::GUATEMALA => __('GUATEMALA'),
            Country::GUERNSEY => __('GUERNSEY'),
            Country::GUINEA => __('GUINEA'),
            Country::GUINEA_BISSAU => __('GUINEA_BISSAU'),
            Country::GUYANA => __('GUYANA'),
            Country::HAITI => __('HAITI'),
            Country::HEARD_ISLAND_AND_MCDONALD_ISLANDS => __('HEARD_ISLAND_AND_MCDONALD_ISLANDS'),
            Country::HOLY_SEE_THE => __('HOLY_SEE_THE'),
            Country::HONDURAS => __('HONDURAS'),
            Country::HONG_KONG => __('HONG_KONG'),
            Country::HUNGARY => __('HUNGARY'),
            Country::ICELAND => __('ICELAND'),
            Country::INDIA => __('INDIA'),
            Country::INDONESIA => __('INDONESIA'),
            Country::IRAN_ISLAMIC_REPUBLIC_OF => __('IRAN_ISLAMIC_REPUBLIC_OF'),
            Country::IRAQ => __('IRAQ'),
            Country::IRELAND => __('IRELAND'),
            Country::ISLE_OF_MAN => __('ISLE_OF_MAN'),
            Country::ISRAEL => __('ISRAEL'),
            Country::ITALY => __('ITALY'),
            Country::JAMAICA => __('JAMAICA'),
            Country::JAPAN => __('JAPAN'),
            Country::JERSEY => __('JERSEY'),
            Country::JORDAN => __('JORDAN'),
            Country::KAZAKHSTAN => __('KAZAKHSTAN'),
            Country::KENYA => __('KENYA'),
            Country::KIRIBATI => __('KIRIBATI'),
            Country::KOREA_THE_DEMOCRATIC_PEOPLE_S_REPUBLIC_OF => __('KOREA_THE_DEMOCRATIC_PEOPLE_S_REPUBLIC_OF'),
            Country::KOREA_THE_REPUBLIC_OF => __('KOREA_THE_REPUBLIC_OF'),
            Country::KUWAIT => __('KUWAIT'),
            Country::KYRGYZSTAN => __('KYRGYZSTAN'),
            Country::LAO_PEOPLE_S_DEMOCRATIC_REPUBLIC_THE => __('LAO_PEOPLE_S_DEMOCRATIC_REPUBLIC_THE'),
            Country::LATVIA => __('LATVIA'),
            Country::LEBANON => __('LEBANON'),
            Country::LESOTHO => __('LESOTHO'),
            Country::LIBERIA => __('LIBERIA'),
            Country::LIBYA => __('LIBYA'),
            Country::LIECHTENSTEIN => __('LIECHTENSTEIN'),
            Country::LITHUANIA => __('LITHUANIA'),
            Country::LUXEMBOURG => __('LUXEMBOURG'),
            Country::MACAO => __('MACAO'),
            Country::MADAGASCAR => __('MADAGASCAR'),
            Country::MALAWI => __('MALAWI'),
            Country::MALAYSIA => __('MALAYSIA'),
            Country::MALDIVES => __('MALDIVES'),
            Country::MALI => __('MALI'),
            Country::MALTA => __('MALTA'),
            Country::MARSHALL_ISLANDS_THE => __('MARSHALL_ISLANDS_THE'),
            Country::MARTINIQUE => __('MARTINIQUE'),
            Country::MAURITANIA => __('MAURITANIA'),
            Country::MAURITIUS => __('MAURITIUS'),
            Country::MAYOTTE => __('MAYOTTE'),
            Country::MEXICO => __('MEXICO'),
            Country::MICRONESIA_FEDERATED_STATES_OF => __('MICRONESIA_FEDERATED_STATES_OF'),
            Country::MOLDOVA_THE_REPUBLIC_OF => __('MOLDOVA_THE_REPUBLIC_OF'),
            Country::MONACO => __('MONACO'),
            Country::MONGOLIA => __('MONGOLIA'),
            Country::MONTENEGRO => __('MONTENEGRO'),
            Country::MONTSERRAT => __('MONTSERRAT'),
            Country::MOROCCO => __('MOROCCO'),
            Country::MOZAMBIQUE => __('MOZAMBIQUE'),
            Country::MYANMAR => __('MYANMAR'),
            Country::NAMIBIA => __('NAMIBIA'),
            Country::NAURU => __('NAURU'),
            Country::NEPAL => __('NEPAL'),
            Country::NETHERLANDS_THE => __('NETHERLANDS_THE'),
            Country::NEW_CALEDONIA => __('NEW_CALEDONIA'),
            Country::NEW_ZEALAND => __('NEW_ZEALAND'),
            Country::NICARAGUA => __('NICARAGUA'),
            Country::NIGER_THE => __('NIGER_THE'),
            Country::NIGERIA => __('NIGERIA'),
            Country::NIUE => __('NIUE'),
            Country::NORFOLK_ISLAND => __('NORFOLK_ISLAND'),
            Country::NORTH_MACEDONIA => __('NORTH_MACEDONIA'),
            Country::NORTHERN_MARIANA_ISLANDS_THE => __('NORTHERN_MARIANA_ISLANDS_THE'),
            Country::NORWAY => __('NORWAY'),
            Country::OMAN => __('OMAN'),
            Country::PAKISTAN => __('PAKISTAN'),
            Country::PALAU => __('PALAU'),
            Country::PALESTINE_STATE_OF => __('PALESTINE_STATE_OF'),
            Country::PANAMA => __('PANAMA'),
            Country::PAPUA_NEW_GUINEA => __('PAPUA_NEW_GUINEA'),
            Country::PARAGUAY => __('PARAGUAY'),
            Country::PERU => __('PERU'),
            Country::PHILIPPINES_THE => __('PHILIPPINES_THE'),
            Country::PITCAIRN => __('PITCAIRN'),
            Country::POLAND => __('POLAND'),
            Country::PORTUGAL => __('PORTUGAL'),
            Country::PUERTO_RICO => __('PUERTO_RICO'),
            Country::QATAR => __('QATAR'),
            Country::REUNION => __('REUNION'),
            Country::ROMANIA => __('ROMANIA'),
            Country::RUSSIAN_FEDERATION_THE => __('RUSSIAN_FEDERATION_THE'),
            Country::RWANDA => __('RWANDA'),
            Country::SAINT_BARTHELEMY => __('SAINT_BARTHELEMY'),
            Country::SAINT_HELENA_ASCENSION_AND_TRISTAN_DA_CUNHA => __('SAINT_HELENA_ASCENSION_AND_TRISTAN_DA_CUNHA'),
            Country::SAINT_KITTS_AND_NEVIS => __('SAINT_KITTS_AND_NEVIS'),
            Country::SAINT_LUCIA => __('SAINT_LUCIA'),
            Country::SAINT_MARTIN_FRENCH_PART => __('SAINT_MARTIN_FRENCH_PART'),
            Country::SAINT_PIERRE_AND_MIQUELON => __('SAINT_PIERRE_AND_MIQUELON'),
            Country::SAINT_VINCENT_AND_THE_GRENADINES => __('SAINT_VINCENT_AND_THE_GRENADINES'),
            Country::SAMOA => __('SAMOA'),
            Country::SAN_MARINO => __('SAN_MARINO'),
            Country::SAO_TOME_AND_PRINCIPE => __('SAO_TOME_AND_PRINCIPE'),
            Country::SAUDI_ARABIA => __('SAUDI_ARABIA'),
            Country::SENEGAL => __('SENEGAL'),
            Country::SERBIA => __('SERBIA'),
            Country::SEYCHELLES => __('SEYCHELLES'),
            Country::SIERRA_LEONE => __('SIERRA_LEONE'),
            Country::SINGAPORE => __('SINGAPORE'),
            Country::SINT_MAARTEN_DUTCH_PART => __('SINT_MAARTEN_DUTCH_PART'),
            Country::SLOVAKIA => __('SLOVAKIA'),
            Country::SLOVENIA => __('SLOVENIA'),
            Country::SOLOMON_ISLANDS => __('SOLOMON_ISLANDS'),
            Country::SOMALIA => __('SOMALIA'),
            Country::SOUTH_AFRICA => __('SOUTH_AFRICA'),
            Country::SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS => __('SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS'),
            Country::SOUTH_SUDAN => __('SOUTH_SUDAN'),
            Country::SPAIN => __('SPAIN'),
            Country::SRI_LANKA => __('SRI_LANKA'),
            Country::SUDAN_THE => __('SUDAN_THE'),
            Country::SURINAME => __('SURINAME'),
            Country::SVALBARD_AND_JAN_MAYEN => __('SVALBARD_AND_JAN_MAYEN'),
            Country::SWEDEN => __('SWEDEN'),
            Country::SWITZERLAND => __('SWITZERLAND'),
            Country::SYRIAN_ARAB_REPUBLIC_THE => __('SYRIAN_ARAB_REPUBLIC_THE'),
            Country::TAIWAN_PROVINCE_OF_CHINA => __('TAIWAN_PROVINCE_OF_CHINA'),
            Country::TAJIKISTAN => __('TAJIKISTAN'),
            Country::TANZANIA_THE_UNITED_REPUBLIC_OF => __('TANZANIA_THE_UNITED_REPUBLIC_OF'),
            Country::THAILAND => __('THAILAND'),
            Country::TIMOR_LESTE => __('TIMOR_LESTE'),
            Country::TOGO => __('TOGO'),
            Country::TOKELAU => __('TOKELAU'),
            Country::TONGA => __('TONGA'),
            Country::TRINIDAD_AND_TOBAGO => __('TRINIDAD_AND_TOBAGO'),
            Country::TUNISIA => __('TUNISIA'),
            Country::TURKEY => __('TURKEY'),
            Country::TURKMENISTAN => __('TURKMENISTAN'),
            Country::TURKS_AND_CAICOS_ISLANDS_THE => __('TURKS_AND_CAICOS_ISLANDS_THE'),
            Country::TUVALU => __('TUVALU'),
            Country::UGANDA => __('UGANDA'),
            Country::UKRAINE => __('UKRAINE'),
            Country::UNITED_ARAB_EMIRATES_THE => __('UNITED_ARAB_EMIRATES_THE'),
            Country::UNITED_KINGDOM_OF_GREAT_BRITAIN_AND_NORTHERN_IRELAND_THE => __('UNITED_KINGDOM_OF_GREAT_BRITAIN_AND_NORTHERN_IRELAND_THE'),
            Country::UNITED_STATES_MINOR_OUTLYING_ISLANDS_THE => __('UNITED_STATES_MINOR_OUTLYING_ISLANDS_THE'),
            Country::UNITED_STATES_OF_AMERICA_THE => __('UNITED_STATES_OF_AMERICA_THE'),
            Country::URUGUAY => __('URUGUAY'),
            Country::UZBEKISTAN => __('UZBEKISTAN'),
            Country::VANUATU => __('VANUATU'),
            Country::VENEZUELA_BOLIVARIAN_REPUBLIC_OF => __('VENEZUELA_BOLIVARIAN_REPUBLIC_OF'),
            Country::VIET_NAM => __('VIET_NAM'),
            Country::VIRGIN_ISLANDS_BRITISH => __('VIRGIN_ISLANDS_BRITISH'),
            Country::VIRGIN_ISLANDS_U_S => __('VIRGIN_ISLANDS_U_S'),
            Country::WALLIS_AND_FUTUNA => __('WALLIS_AND_FUTUNA'),
            Country::WESTERN_SAHARA => __('WESTERN_SAHARA'),
            Country::YEMEN => __('YEMEN'),
            Country::ZAMBIA => __('ZAMBIA'),
            Country::ZIMBABWE => __('ZIMBABWE'),
        };
    }

    public function alpha3(): string
    {
        return match ($this) {
            Country::AFGHANISTAN => 'AFG',
            Country::ALAND_ISLANDS => 'ALA',
            Country::ALBANIA => 'ALB',
            Country::ALGERIA => 'DZA',
            Country::AMERICAN_SAMOA => 'ASM',
            Country::ANDORRA => 'AND',
            Country::ANGOLA => 'AGO',
            Country::ANGUILLA => 'AIA',
            Country::ANTIGUA_AND_BARBUDA => 'ATG',
            Country::ARGENTINA => 'ARG',
            Country::ARMENIA => 'ARM',
            Country::ARUBA => 'ABW',
            Country::AUSTRALIA => 'AUS',
            Country::AUSTRIA => 'AUT',
            Country::AZERBAIJAN => 'AZE',
            Country::BAHAMAS_THE => 'BHS',
            Country::BAHRAIN => 'BHR',
            Country::BANGLADESH => 'BGD',
            Country::BARBADOS => 'BRB',
            Country::BELARUS => 'BLR',
            Country::BELGIUM => 'BEL',
            Country::BELIZE => 'BLZ',
            Country::BENIN => 'BEN',
            Country::BERMUDA => 'BMU',
            Country::BHUTAN => 'BTN',
            Country::BOLIVIA_PLURINATIONAL_STATE_OF => 'BOL',
            Country::BONAIRE_SINT_EUSTATIUS_AND_SABA => 'BES',
            Country::BOSNIA_AND_HERZEGOVINA => 'BIH',
            Country::BOTSWANA => 'BWA',
            Country::BOUVET_ISLAND => 'BVT',
            Country::BRAZIL => 'BRA',
            Country::BRITISH_INDIAN_OCEAN_TERRITORY_THE => 'IOT',
            Country::BRUNEI_DARUSSALAM => 'BRN',
            Country::BULGARIA => 'BGR',
            Country::BURKINA_FASO => 'BFA',
            Country::BURUNDI => 'BDI',
            Country::CABO_VERDE => 'CPV',
            Country::CAMBODIA => 'KHM',
            Country::CAMEROON => 'CMR',
            Country::CANADA => 'CAN',
            Country::CAYMAN_ISLANDS_THE => 'CYM',
            Country::CENTRAL_AFRICAN_REPUBLIC_THE => 'CAF',
            Country::CHAD => 'TCD',
            Country::CHILE => 'CHL',
            Country::CHINA => 'CHN',
            Country::CHRISTMAS_ISLAND => 'CXR',
            Country::COCOS_KEELING_ISLANDS_THE => 'CCK',
            Country::COLOMBIA => 'COL',
            Country::COMOROS_THE => 'COM',
            Country::CONGO_THE => 'COG',
            Country::CONGO_THE_DEMOCRATIC_REPUBLIC_OF_THE => 'COD',
            Country::COOK_ISLANDS_THE => 'COK',
            Country::COSTA_RICA => 'CRI',
            Country::COTE_D_IVOIRE => 'CIV',
            Country::CROATIA => 'HRV',
            Country::CUBA => 'CUB',
            Country::CURACAO => 'CUW',
            Country::CYPRUS => 'CYP',
            Country::CZECHIA => 'CZE',
            Country::DENMARK => 'DNK',
            Country::DJIBOUTI => 'DJI',
            Country::DOMINICA => 'DMA',
            Country::DOMINICAN_REPUBLIC_THE => 'DOM',
            Country::ECUADOR => 'ECU',
            Country::EGYPT => 'EGY',
            Country::EL_SALVADOR => 'SLV',
            Country::EQUATORIAL_GUINEA => 'GNQ',
            Country::ERITREA => 'ERI',
            Country::ESTONIA => 'EST',
            Country::ESWATINI => 'SWZ',
            Country::ETHIOPIA => 'ETH',
            Country::FALKLAND_ISLANDS_THE_MALVINAS => 'FLK',
            Country::FAROE_ISLANDS_THE => 'FRO',
            Country::FIJI => 'FJI',
            Country::FINLAND => 'FIN',
            Country::FRANCE => 'FRA',
            Country::FRENCH_GUIANA => 'GUF',
            Country::FRENCH_POLYNESIA => 'PYF',
            Country::FRENCH_SOUTHERN_TERRITORIES_THE => 'ATF',
            Country::GABON => 'GAB',
            Country::GAMBIA_THE => 'GMB',
            Country::GEORGIA => 'GEO',
            Country::GERMANY => 'DEU',
            Country::GHANA => 'GHA',
            Country::GIBRALTAR => 'GIB',
            Country::GREECE => 'GRC',
            Country::GREENLAND => 'GRL',
            Country::GRENADA => 'GRD',
            Country::GUADELOUPE => 'GLP',
            Country::GUAM => 'GUM',
            Country::GUATEMALA => 'GTM',
            Country::GUERNSEY => 'GGY',
            Country::GUINEA => 'GIN',
            Country::GUINEA_BISSAU => 'GNB',
            Country::GUYANA => 'GUY',
            Country::HAITI => 'HTI',
            Country::HEARD_ISLAND_AND_MCDONALD_ISLANDS => 'HMD',
            Country::HOLY_SEE_THE => 'VAT',
            Country::HONDURAS => 'HND',
            Country::HONG_KONG => 'HKG',
            Country::HUNGARY => 'HUN',
            Country::ICELAND => 'ISL',
            Country::INDIA => 'IND',
            Country::INDONESIA => 'IDN',
            Country::IRAN_ISLAMIC_REPUBLIC_OF => 'IRN',
            Country::IRAQ => 'IRQ',
            Country::IRELAND => 'IRL',
            Country::ISLE_OF_MAN => 'IMN',
            Country::ISRAEL => 'ISR',
            Country::ITALY => 'ITA',
            Country::JAMAICA => 'JAM',
            Country::JAPAN => 'JPN',
            Country::JERSEY => 'JEY',
            Country::JORDAN => 'JOR',
            Country::KAZAKHSTAN => 'KAZ',
            Country::KENYA => 'KEN',
            Country::KIRIBATI => 'KIR',
            Country::KOREA_THE_DEMOCRATIC_PEOPLE_S_REPUBLIC_OF => 'PRK',
            Country::KOREA_THE_REPUBLIC_OF => 'KOR',
            Country::KUWAIT => 'KWT',
            Country::KYRGYZSTAN => 'KGZ',
            Country::LAO_PEOPLE_S_DEMOCRATIC_REPUBLIC_THE => 'LAO',
            Country::LATVIA => 'LVA',
            Country::LEBANON => 'LBN',
            Country::LESOTHO => 'LSO',
            Country::LIBERIA => 'LBR',
            Country::LIBYA => 'LBY',
            Country::LIECHTENSTEIN => 'LIE',
            Country::LITHUANIA => 'LTU',
            Country::LUXEMBOURG => 'LUX',
            Country::MACAO => 'MAC',
            Country::MADAGASCAR => 'MDG',
            Country::MALAWI => 'MWI',
            Country::MALAYSIA => 'MYS',
            Country::MALDIVES => 'MDV',
            Country::MALI => 'MLI',
            Country::MALTA => 'MLT',
            Country::MARSHALL_ISLANDS_THE => 'MHL',
            Country::MARTINIQUE => 'MTQ',
            Country::MAURITANIA => 'MRT',
            Country::MAURITIUS => 'MUS',
            Country::MAYOTTE => 'MYT',
            Country::MEXICO => 'MEX',
            Country::MICRONESIA_FEDERATED_STATES_OF => 'FSM',
            Country::MOLDOVA_THE_REPUBLIC_OF => 'MDA',
            Country::MONACO => 'MCO',
            Country::MONGOLIA => 'MNG',
            Country::MONTENEGRO => 'MNE',
            Country::MONTSERRAT => 'MSR',
            Country::MOROCCO => 'MAR',
            Country::MOZAMBIQUE => 'MOZ',
            Country::MYANMAR => 'MMR',
            Country::NAMIBIA => 'NAM',
            Country::NAURU => 'NRU',
            Country::NEPAL => 'NPL',
            Country::NETHERLANDS_THE => 'NLD',
            Country::NEW_CALEDONIA => 'NCL',
            Country::NEW_ZEALAND => 'NZL',
            Country::NICARAGUA => 'NIC',
            Country::NIGER_THE => 'NER',
            Country::NIGERIA => 'NGA',
            Country::NIUE => 'NIU',
            Country::NORFOLK_ISLAND => 'NFK',
            Country::NORTH_MACEDONIA => 'MKD',
            Country::NORTHERN_MARIANA_ISLANDS_THE => 'MNP',
            Country::NORWAY => 'NOR',
            Country::OMAN => 'OMN',
            Country::PAKISTAN => 'PAK',
            Country::PALAU => 'PLW',
            Country::PALESTINE_STATE_OF => 'PSE',
            Country::PANAMA => 'PAN',
            Country::PAPUA_NEW_GUINEA => 'PNG',
            Country::PARAGUAY => 'PRY',
            Country::PERU => 'PER',
            Country::PHILIPPINES_THE => 'PHL',
            Country::PITCAIRN => 'PCN',
            Country::POLAND => 'POL',
            Country::PORTUGAL => 'PRT',
            Country::PUERTO_RICO => 'PRI',
            Country::QATAR => 'QAT',
            Country::REUNION => 'REU',
            Country::ROMANIA => 'ROU',
            Country::RUSSIAN_FEDERATION_THE => 'RUS',
            Country::RWANDA => 'RWA',
            Country::SAINT_BARTHELEMY => 'BLM',
            Country::SAINT_HELENA_ASCENSION_AND_TRISTAN_DA_CUNHA => 'SHN',
            Country::SAINT_KITTS_AND_NEVIS => 'KNA',
            Country::SAINT_LUCIA => 'LCA',
            Country::SAINT_MARTIN_FRENCH_PART => 'MAF',
            Country::SAINT_PIERRE_AND_MIQUELON => 'SPM',
            Country::SAINT_VINCENT_AND_THE_GRENADINES => 'VCT',
            Country::SAMOA => 'WSM',
            Country::SAN_MARINO => 'SMR',
            Country::SAO_TOME_AND_PRINCIPE => 'STP',
            Country::SAUDI_ARABIA => 'SAU',
            Country::SENEGAL => 'SEN',
            Country::SERBIA => 'SRB',
            Country::SEYCHELLES => 'SYC',
            Country::SIERRA_LEONE => 'SLE',
            Country::SINGAPORE => 'SGP',
            Country::SINT_MAARTEN_DUTCH_PART => 'SXM',
            Country::SLOVAKIA => 'SVK',
            Country::SLOVENIA => 'SVN',
            Country::SOLOMON_ISLANDS => 'SLB',
            Country::SOMALIA => 'SOM',
            Country::SOUTH_AFRICA => 'ZAF',
            Country::SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS => 'SGS',
            Country::SOUTH_SUDAN => 'SSD',
            Country::SPAIN => 'ESP',
            Country::SRI_LANKA => 'LKA',
            Country::SUDAN_THE => 'SDN',
            Country::SURINAME => 'SUR',
            Country::SVALBARD_AND_JAN_MAYEN => 'SJM',
            Country::SWEDEN => 'SWE',
            Country::SWITZERLAND => 'CHE',
            Country::SYRIAN_ARAB_REPUBLIC_THE => 'SYR',
            Country::TAIWAN_PROVINCE_OF_CHINA => 'TWN',
            Country::TAJIKISTAN => 'TJK',
            Country::TANZANIA_THE_UNITED_REPUBLIC_OF => 'TZA',
            Country::THAILAND => 'THA',
            Country::TIMOR_LESTE => 'TLS',
            Country::TOGO => 'TGO',
            Country::TOKELAU => 'TKL',
            Country::TONGA => 'TON',
            Country::TRINIDAD_AND_TOBAGO => 'TTO',
            Country::TUNISIA => 'TUN',
            Country::TURKEY => 'TUR',
            Country::TURKMENISTAN => 'TKM',
            Country::TURKS_AND_CAICOS_ISLANDS_THE => 'TCA',
            Country::TUVALU => 'TUV',
            Country::UGANDA => 'UGA',
            Country::UKRAINE => 'UKR',
            Country::UNITED_ARAB_EMIRATES_THE => 'ARE',
            Country::UNITED_KINGDOM_OF_GREAT_BRITAIN_AND_NORTHERN_IRELAND_THE => 'GBR',
            Country::UNITED_STATES_MINOR_OUTLYING_ISLANDS_THE => 'UMI',
            Country::UNITED_STATES_OF_AMERICA_THE => 'USA',
            Country::URUGUAY => 'URY',
            Country::UZBEKISTAN => 'UZB',
            Country::VANUATU => 'VUT',
            Country::VENEZUELA_BOLIVARIAN_REPUBLIC_OF => 'VEN',
            Country::VIET_NAM => 'VNM',
            Country::VIRGIN_ISLANDS_BRITISH => 'VGB',
            Country::VIRGIN_ISLANDS_U_S => 'VIR',
            Country::WALLIS_AND_FUTUNA => 'WLF',
            Country::WESTERN_SAHARA => 'ESH',
            Country::YEMEN => 'YEM',
            Country::ZAMBIA => 'ZMB',
            Country::ZIMBABWE => 'ZWE',
        };
    }

    /**
     * Get the Continent of a Country
     */
    public function continent(): Continent
    {
        $continentId = substr($this->value, 0, 1);

        return Continent::from($continentId);
    }

    /**
     * Get all Districts of a Country
     */
    public function districts(): array
    {
        return array_filter(
            District::cases(),
            fn (District $enum) => substr($enum->value, 0, 4) === $this->value
        );
    }

    /**
     * Get all Districts of a Country
     */
    public function counties(): array
    {
        return array_filter(
            County::cases(),
            fn (County $enum) => substr($enum->value, 0, 4) === $this->value
        );
    }
}
