<?php

namespace App\Models\Enums\Territory;

use App\Models\Traits\EnumToArray;

enum County: string
{
    use EnumToArray;

    case AGUEDA = '317900101';
    case ALBERGARIA_A_VELHA = '317900102';
    case ANADIA = '317900103';
    case AROUCA = '317900104';
    case AVEIRO = '317900105';
    case CASTELO_DE_PAIVA = '317900106';
    case ESPINHO = '317900107';
    case ESTARREJA = '317900108';
    case SANTA_MARIA_DA_FEIRA = '317900109';
    case ILHAVO = '317900110';
    case MEALHADA = '317900111';
    case MURTOSA = '317900112';
    case OLIVEIRA_DE_AZEMEIS = '317900113';
    case OLIVEIRA_DO_BAIRRO = '317900114';
    case OVAR = '317900115';
    case SAO_JOAO_DA_MADEIRA = '317900116';
    case SEVER_DO_VOUGA = '317900117';
    case VAGOS = '317900118';
    case VALE_DE_CAMBRA = '317900119';
    case ALJUSTREL = '317900201';
    case ALMODOVAR = '317900202';
    case ALVITO = '317900203';
    case BARRANCOS = '317900204';
    case BEJA = '317900205';
    case CASTRO_VERDE = '317900206';
    case CUBA = '317900207';
    case FERREIRA_DO_ALENTEJO = '317900208';
    case MERTOLA = '317900209';
    case MOURA = '317900210';
    case ODEMIRA = '317900211';
    case OURIQUE = '317900212';
    case SERPA = '317900213';
    case VIDIGUEIRA = '317900214';
    case AMARES = '317900301';
    case BARCELOS = '317900302';
    case BRAGA = '317900303';
    case CABECEIRAS_DE_BASTO = '317900304';
    case CELORICO_DE_BASTO = '317900305';
    case ESPOSENDE = '317900306';
    case FAFE = '317900307';
    case GUIMARAES = '317900308';
    case POVOA_DE_LANHOSO = '317900309';
    case TERRAS_DE_BOURO = '317900310';
    case VIEIRA_DO_MINHO = '317900311';
    case VILA_NOVA_DE_FAMALICAO = '317900312';
    case VILA_VERDE = '317900313';
    case VIZELA = '317900314';
    case ALFANDEGA_DA_FE = '317900401';
    case BRAGANÇA = '317900402';
    case CARRAZEDA_DE_ANSIÃES = '317900403';
    case FREIXO_DE_ESPADA_A_CINTA = '317900404';
    case MACEDO_DE_CAVALEIROS = '317900405';
    case MIRANDA_DO_DOURO = '317900406';
    case MIRANDELA = '317900407';
    case MOGADOURO = '317900408';
    case TORRE_DE_MONCORVO = '317900409';
    case VILA_FLOR = '317900410';
    case VIMIOSO = '317900411';
    case VINHAIS = '317900412';
    case BELMONTE = '317900501';
    case CASTELO_BRANCO = '317900502';
    case COVILHA = '317900503';
    case FUNDAO = '317900504';
    case IDANHA_A_NOVA = '317900505';
    case OLEIROS = '317900506';
    case PENAMACOR = '317900507';
    case PROENCA_A_NOVA = '317900508';
    case SERTA = '317900509';
    case VILA_DE_REI = '317900510';
    case VILA_VELHA_DE_RODAO = '317900511';
    case ARGANIL = '317900601';
    case CANTANHEDE = '317900602';
    case COIMBRA = '317900603';
    case CONDEIXA_A_NOVA = '317900604';
    case FIGUEIRA_DA_FOZ = '317900605';
    case GOIS = '317900606';
    case LOUSA = '317900607';
    case MIRA = '317900608';
    case MIRANDA_DO_CORVO = '317900609';
    case MONTEMOR_O_VELHO = '317900610';
    case OLIVEIRA_DO_HOSPITAL = '317900611';
    case PAMPILHOSA_DA_SERRA = '317900612';
    case PENACOVA = '317900613';
    case PENELA = '317900614';
    case SOURE = '317900615';
    case TABUA = '317900616';
    case VILA_NOVA_DE_POIARES = '317900617';
    case ALANDROAL = '317900701';
    case ARRAIOLOS = '317900702';
    case BORBA = '317900703';
    case ESTREMOZ = '317900704';
    case EVORA = '317900705';
    case MONTEMOR_O_NOVO = '317900706';
    case MORA = '317900707';
    case MOURAO = '317900708';
    case PORTEL = '317900709';
    case REDONDO = '317900710';
    case REGUENGOS_DE_MONSARAZ = '317900711';
    case VENDAS_NOVAS = '317900712';
    case VIANA_DO_ALENTEJO = '317900713';
    case VILA_VICOSA = '317900714';
    case ALBUFEIRA = '317900801';
    case ALCOUTIM = '317900802';
    case ALJEZUR = '317900803';
    case CASTRO_MARIM = '317900804';
    case FARO = '317900805';
    case LAGOA = '317900806';
    case LAGOS = '317900807';
    case LOULE = '317900808';
    case MONCHIQUE = '317900809';
    case OLHAO = '317900810';
    case PORTIMAO = '317900811';
    case SAO_BRAS_DE_ALPORTEL = '317900812';
    case SILVES = '317900813';
    case TAVIRA = '317900814';
    case VILA_DO_BISPO = '317900815';
    case VILA_REAL_DE_SANTO_ANTONIO = '317900816';
    case AGUIAR_DA_BEIRA = '317900901';
    case ALMEIDA = '317900902';
    case CELORICO_DA_BEIRA = '317900903';
    case FIGUEIRA_DE_CASTELO_RODRIGO = '317900904';
    case FORNOS_DE_ALGODRES = '317900905';
    case GOUVEIA = '317900906';
    case GUARDA = '317900907';
    case MANTEIGAS = '317900908';
    case MEDA = '317900909';
    case PINHEL = '317900910';
    case SABUGAL = '317900911';
    case SEIA = '317900912';
    case TRANCOSO = '317900913';
    case VILA_NOVA_DE_FOZ_COA = '317900914';
    case ALCOBACA = '317901001';
    case ALVAIAZERE = '317901002';
    case ANSIAO = '317901003';
    case BATALHA = '317901004';
    case BOMBARRAL = '317901005';
    case CALDAS_DA_RAINHA = '317901006';
    case CASTANHEIRA_DE_PERA = '317901007';
    case FIGUEIRO_DOS_VINHOS = '317901008';
    case LEIRIA = '317901009';
    case MARINHA_GRANDE = '317901010';
    case NAZARE = '317901011';
    case OBIDOS = '317901012';
    case PEDROGAO_GRANDE = '317901013';
    case PENICHE = '317901014';
    case POMBAL = '317901015';
    case PORTO_DE_MOS = '317901016';
    case ALENQUER = '317901101';
    case ARRUDA_DOS_VINHOS = '317901102';
    case AZAMBUJA = '317901103';
    case CADAVAL = '317901104';
    case CASCAIS = '317901105';
    case LISBOA = '317901106';
    case LOURES = '317901107';
    case LOURINHA = '317901108';
    case MAFRA = '317901109';
    case OEIRAS = '317901110';
    case SINTRA = '317901111';
    case SOBRAL_DE_MONTE_AGRACO = '317901112';
    case TORRES_VEDRAS = '317901113';
    case VILA_FRANCA_DE_XIRA = '317901114';
    case AMADORA = '317901115';
    case ODIVELAS = '317901116';
    case ALTER_DO_CHAO = '317901201';
    case ARRONCHES = '317901202';
    case AVIS = '317901203';
    case CAMPO_MAIOR = '317901204';
    case CASTELO_DE_VIDE = '317901205';
    case CRATO = '317901206';
    case ELVAS = '317901207';
    case FRONTEIRA = '317901208';
    case GAVIAO = '317901209';
    case MARVAO = '317901210';
    case MONFORTE = '317901211';
    case NISA = '317901212';
    case PONTE_DE_SOR = '317901213';
    case PORTALEGRE = '317901214';
    case SOUSEL = '317901215';
    case AMARANTE = '317901301';
    case BAIAO = '317901302';
    case FELGUEIRAS = '317901303';
    case GONDOMAR = '317901304';
    case LOUSADA = '317901305';
    case MAIA = '317901306';
    case MARCO_DE_CANAVESES = '317901307';
    case MATOSINHOS = '317901308';
    case PACOS_DE_FERREIRA = '317901309';
    case PAREDES = '317901310';
    case PENAFIEL = '317901311';
    case PORTO = '317901312';
    case POVOA_DE_VARZIM = '317901313';
    case SANTO_TIRSO = '317901314';
    case VALONGO = '317901315';
    case VILA_DO_CONDE = '317901316';
    case VILA_NOVA_DE_GAIA = '317901317';
    case TROFA = '317901318';
    case ABRANTES = '317901401';
    case ALCANENA = '317901402';
    case ALMEIRIM = '317901403';
    case ALPIARCA = '317901404';
    case BENAVENTE = '317901405';
    case CARTAXO = '317901406';
    case CHAMUSCA = '317901407';
    case CONSTANCIA = '317901408';
    case CORUCHE = '317901409';
    case ENTRONCAMENTO = '317901410';
    case FERREIRA_DO_ZEZERE = '317901411';
    case GOLEGA = '317901412';
    case MACAO = '317901413';
    case RIO_MAIOR = '317901414';
    case SALVATERRA_DE_MAGOS = '317901415';
    case SANTAREM = '317901416';
    case SARDOAL = '317901417';
    case TOMAR = '317901418';
    case TORRES_NOVAS = '317901419';
    case VILA_NOVA_DA_BARQUINHA = '317901420';
    case OUREM = '317901421';
    case ALCACER_DO_SAL = '317901501';
    case ALCOCHETE = '317901502';
    case ALMADA = '317901503';
    case BARREIRO = '317901504';
    case GRANDOLA = '317901505';
    case MOITA = '317901506';
    case MONTIJO = '317901507';
    case PALMELA = '317901508';
    case SANTIAGO_DO_CACEM = '317901509';
    case SEIXAL = '317901510';
    case SESIMBRA = '317901511';
    case SETUBAL = '317901512';
    case SINES = '317901513';
    case ARCOS_DE_VALDEVEZ = '317901601';
    case CAMINHA = '317901602';
    case MELGACO = '317901603';
    case MONCAO = '317901604';
    case PAREDES_DE_COURA = '317901605';
    case PONTE_DA_BARCA = '317901606';
    case PONTE_DE_LIMA = '317901607';
    case VALENÇA = '317901608';
    case VIANA_DO_CASTELO = '317901609';
    case VILA_NOVA_DE_CERVEIRA = '317901610';
    case ALIJO = '317901701';
    case BOTICAS = '317901702';
    case CHAVES = '317901703';
    case MESAO_FRIO = '317901704';
    case MONDIM_DE_BASTO = '317901705';
    case MONTALEGRE = '317901706';
    case MURÇA = '317901707';
    case PESO_DA_REGUA = '317901708';
    case RIBEIRA_DE_PENA = '317901709';
    case SABROSA = '317901710';
    case SANTA_MARTA_DE_PENAGUIAO = '317901711';
    case VALPACOS = '317901712';
    case VILA_POUCA_DE_AGUIAR = '317901713';
    case VILA_REAL = '317901714';
    case ARMAMAR = '317901801';
    case CARREGAL_DO_SAL = '317901802';
    case CASTRO_DAIRE = '317901803';
    case CINFAES = '317901804';
    case LAMEGO = '317901805';
    case MANGUALDE = '317901806';
    case MOIMENTA_DA_BEIRA = '317901807';
    case MORTAGUA = '317901808';
    case NELAS = '317901809';
    case OLIVEIRA_DE_FRADES = '317901810';
    case PENALVA_DO_CASTELO = '317901811';
    case PENEDONO = '317901812';
    case RESENDE = '317901813';
    case SANTA_COMBA_DAO = '317901814';
    case SAO_JOAO_DA_PESQUEIRA = '317901815';
    case SAO_PEDRO_DO_SUL = '317901816';
    case SATAO = '317901817';
    case SERNANCELHE = '317901818';
    case TABUACO = '317901819';
    case TAROUCA = '317901820';
    case TONDELA = '317901821';
    case VILA_NOVA_DE_PAIVA = '317901822';
    case VISEU = '317901823';
    case VOUZELA = '317901824';
    case CALHETA = '317903101';
    case CAMARA_DE_LOBOS = '317903102';
    case FUNCHAL = '317903103';
    case MACHICO = '317903104';
    case PONTA_DO_SOL = '317903105';
    case PORTO_MONIZ = '317903106';
    case RIBEIRA_BRAVA = '317903107';
    case SANTA_CRUZ = '317903108';
    case SANTANA = '317903109';
    case SAO_VICENTE = '317903110';
    case PORTO_SANTO = '317903201';
    case VILA_DO_PORTO = '317904101';
    case LAGOA_SAO_MIGUEL = '317904201';
    case NORDESTE = '317904202';
    case PONTA_DELGADA = '317904203';
    case POVOACAO = '317904204';
    case RIBEIRA_GRANDE = '317904205';
    case VILA_FRANCA_DO_CAMPO = '317904206';
    case ANGRA_DO_HEROISMO = '317904301';
    case VILA_DA_PRAIA_DA_VITORIA = '317904302';
    case SANTA_CRUZ_DA_GRACIOSA = '317904401';
    case CALHETA_SAO_JORGE = '317904501';
    case VELAS = '317904502';
    case LAJES_DO_PICO = '317904601';
    case MADALENA = '317904602';
    case SAO_ROQUE_DO_PICO = '317904603';
    case HORTA = '317904701';
    case LAJES_DAS_FLORES = '317904801';
    case SANTA_CRUZ_DAS_FLORES = '317904802';
    case CORVO = '317904901';

    public function name(): string
    {
        return match ($this) {
            County::AGUEDA => __('ÁGUEDA'),
            County::ALBERGARIA_A_VELHA => __('ALBERGARIA-A-VELHA'),
            County::ANADIA => __('ANADIA'),
            County::AROUCA => __('AROUCA'),
            County::AVEIRO => __('AVEIRO'),
            County::CASTELO_DE_PAIVA => __('CASTELO DE PAIVA'),
            County::ESPINHO => __('ESPINHO'),
            County::ESTARREJA => __('ESTARREJA'),
            County::SANTA_MARIA_DA_FEIRA => __('SANTA MARIA DA FEIRA'),
            County::ILHAVO => __('ÍLHAVO'),
            County::MEALHADA => __('MEALHADA'),
            County::MURTOSA => __('MURTOSA'),
            County::OLIVEIRA_DE_AZEMEIS => __('OLIVEIRA DE AZEMÉIS'),
            County::OLIVEIRA_DO_BAIRRO => __('OLIVEIRA DO BAIRRO'),
            County::OVAR => __('OVAR'),
            County::SAO_JOAO_DA_MADEIRA => __('SÃO JOÃO DA MADEIRA'),
            County::SEVER_DO_VOUGA => __('SEVER DO VOUGA'),
            County::VAGOS => __('VAGOS'),
            County::VALE_DE_CAMBRA => __('VALE DE CAMBRA'),
            County::ALJUSTREL => __('ALJUSTREL'),
            County::ALMODOVAR => __('ALMODÔVAR'),
            County::ALVITO => __('ALVITO'),
            County::BARRANCOS => __('BARRANCOS'),
            County::BEJA => __('BEJA'),
            County::CASTRO_VERDE => __('CASTRO VERDE'),
            County::CUBA => __('CUBA'),
            County::FERREIRA_DO_ALENTEJO => __('FERREIRA DO ALENTEJO'),
            County::MERTOLA => __('MÉRTOLA'),
            County::MOURA => __('MOURA'),
            County::ODEMIRA => __('ODEMIRA'),
            County::OURIQUE => __('OURIQUE'),
            County::SERPA => __('SERPA'),
            County::VIDIGUEIRA => __('VIDIGUEIRA'),
            County::AMARES => __('AMARES'),
            County::BARCELOS => __('BARCELOS'),
            County::BRAGA => __('BRAGA'),
            County::CABECEIRAS_DE_BASTO => __('CABECEIRAS DE BASTO'),
            County::CELORICO_DE_BASTO => __('CELORICO DE BASTO'),
            County::ESPOSENDE => __('ESPOSENDE'),
            County::FAFE => __('FAFE'),
            County::GUIMARAES => __('GUIMARÃES'),
            County::POVOA_DE_LANHOSO => __('PÓVOA DE LANHOSO'),
            County::TERRAS_DE_BOURO => __('TERRAS DE BOURO'),
            County::VIEIRA_DO_MINHO => __('VIEIRA DO MINHO'),
            County::VILA_NOVA_DE_FAMALICAO => __('VILA NOVA DE FAMALICÃO'),
            County::VILA_VERDE => __('VILA VERDE'),
            County::VIZELA => __('VIZELA'),
            County::ALFANDEGA_DA_FE => __('ALFÂNDEGA DA FÉ'),
            County::BRAGANÇA => __('BRAGANÇA'),
            County::CARRAZEDA_DE_ANSIÃES => __('CARRAZEDA DE ANSIÃES'),
            County::FREIXO_DE_ESPADA_A_CINTA => __('FREIXO DE ESPADA À CINTA'),
            County::MACEDO_DE_CAVALEIROS => __('MACEDO DE CAVALEIROS'),
            County::MIRANDA_DO_DOURO => __('MIRANDA DO DOURO'),
            County::MIRANDELA => __('MIRANDELA'),
            County::MOGADOURO => __('MOGADOURO'),
            County::TORRE_DE_MONCORVO => __('TORRE DE MONCORVO'),
            County::VILA_FLOR => __('VILA FLOR'),
            County::VIMIOSO => __('VIMIOSO'),
            County::VINHAIS => __('VINHAIS'),
            County::BELMONTE => __('BELMONTE'),
            County::CASTELO_BRANCO => __('CASTELO BRANCO'),
            County::COVILHA => __('COVILHÃ'),
            County::FUNDAO => __('FUNDÃO'),
            County::IDANHA_A_NOVA => __('IDANHA-A-NOVA'),
            County::OLEIROS => __('OLEIROS'),
            County::PENAMACOR => __('PENAMACOR'),
            County::PROENCA_A_NOVA => __('PROENÇA-A-NOVA'),
            County::SERTA => __('SERTÃ'),
            County::VILA_DE_REI => __('VILA DE REI'),
            County::VILA_VELHA_DE_RODAO => __('VILA VELHA DE RÓDÃO'),
            County::ARGANIL => __('ARGANIL'),
            County::CANTANHEDE => __('CANTANHEDE'),
            County::COIMBRA => __('COIMBRA'),
            County::CONDEIXA_A_NOVA => __('CONDEIXA-A-NOVA'),
            County::FIGUEIRA_DA_FOZ => __('FIGUEIRA DA FOZ'),
            County::GOIS => __('GÓIS'),
            County::LOUSA => __('LOUSÃ'),
            County::MIRA => __('MIRA'),
            County::MIRANDA_DO_CORVO => __('MIRANDA DO CORVO'),
            County::MONTEMOR_O_VELHO => __('MONTEMOR-O-VELHO'),
            County::OLIVEIRA_DO_HOSPITAL => __('OLIVEIRA DO HOSPITAL'),
            County::PAMPILHOSA_DA_SERRA => __('PAMPILHOSA DA SERRA'),
            County::PENACOVA => __('PENACOVA'),
            County::PENELA => __('PENELA'),
            County::SOURE => __('SOURE'),
            County::TABUA => __('TÁBUA'),
            County::VILA_NOVA_DE_POIARES => __('VILA NOVA DE POIARES'),
            County::ALANDROAL => __('ALANDROAL'),
            County::ARRAIOLOS => __('ARRAIOLOS'),
            County::BORBA => __('BORBA'),
            County::ESTREMOZ => __('ESTREMOZ'),
            County::EVORA => __('ÉVORA'),
            County::MONTEMOR_O_NOVO => __('MONTEMOR-O-NOVO'),
            County::MORA => __('MORA'),
            County::MOURAO => __('MOURÃO'),
            County::PORTEL => __('PORTEL'),
            County::REDONDO => __('REDONDO'),
            County::REGUENGOS_DE_MONSARAZ => __('REGUENGOS DE MONSARAZ'),
            County::VENDAS_NOVAS => __('VENDAS NOVAS'),
            County::VIANA_DO_ALENTEJO => __('VIANA DO ALENTEJO'),
            County::VILA_VICOSA => __('VILA VIÇOSA'),
            County::ALBUFEIRA => __('ALBUFEIRA'),
            County::ALCOUTIM => __('ALCOUTIM'),
            County::ALJEZUR => __('ALJEZUR'),
            County::CASTRO_MARIM => __('CASTRO MARIM'),
            County::FARO => __('FARO'),
            County::LAGOA => __('LAGOA'),
            County::LAGOS => __('LAGOS'),
            County::LOULE => __('LOULÉ'),
            County::MONCHIQUE => __('MONCHIQUE'),
            County::OLHAO => __('OLHÃO'),
            County::PORTIMAO => __('PORTIMÃO'),
            County::SAO_BRAS_DE_ALPORTEL => __('SÃO BRÁS DE ALPORTEL'),
            County::SILVES => __('SILVES'),
            County::TAVIRA => __('TAVIRA'),
            County::VILA_DO_BISPO => __('VILA DO BISPO'),
            County::VILA_REAL_DE_SANTO_ANTONIO => __('VILA REAL DE SANTO ANTÓNIO'),
            County::AGUIAR_DA_BEIRA => __('AGUIAR DA BEIRA'),
            County::ALMEIDA => __('ALMEIDA'),
            County::CELORICO_DA_BEIRA => __('CELORICO DA BEIRA'),
            County::FIGUEIRA_DE_CASTELO_RODRIGO => __('FIGUEIRA DE CASTELO RODRIGO'),
            County::FORNOS_DE_ALGODRES => __('FORNOS DE ALGODRES'),
            County::GOUVEIA => __('GOUVEIA'),
            County::GUARDA => __('GUARDA'),
            County::MANTEIGAS => __('MANTEIGAS'),
            County::MEDA => __('MÊDA'),
            County::PINHEL => __('PINHEL'),
            County::SABUGAL => __('SABUGAL'),
            County::SEIA => __('SEIA'),
            County::TRANCOSO => __('TRANCOSO'),
            County::VILA_NOVA_DE_FOZ_COA => __('VILA NOVA DE FOZ CÔA'),
            County::ALCOBACA => __('ALCOBAÇA'),
            County::ALVAIAZERE => __('ALVAIÁZERE'),
            County::ANSIAO => __('ANSIÃO'),
            County::BATALHA => __('BATALHA'),
            County::BOMBARRAL => __('BOMBARRAL'),
            County::CALDAS_DA_RAINHA => __('CALDAS DA RAINHA'),
            County::CASTANHEIRA_DE_PERA => __('CASTANHEIRA DE PÊRA'),
            County::FIGUEIRO_DOS_VINHOS => __('FIGUEIRÓ DOS VINHOS'),
            County::LEIRIA => __('LEIRIA'),
            County::MARINHA_GRANDE => __('MARINHA GRANDE'),
            County::NAZARE => __('NAZARÉ'),
            County::OBIDOS => __('ÓBIDOS'),
            County::PEDROGAO_GRANDE => __('PEDRÓGÃO GRANDE'),
            County::PENICHE => __('PENICHE'),
            County::POMBAL => __('POMBAL'),
            County::PORTO_DE_MOS => __('PORTO DE MÓS'),
            County::ALENQUER => __('ALENQUER'),
            County::ARRUDA_DOS_VINHOS => __('ARRUDA DOS VINHOS'),
            County::AZAMBUJA => __('AZAMBUJA'),
            County::CADAVAL => __('CADAVAL'),
            County::CASCAIS => __('CASCAIS'),
            County::LISBOA => __('LISBOA'),
            County::LOURES => __('LOURES'),
            County::LOURINHA => __('LOURINHÃ'),
            County::MAFRA => __('MAFRA'),
            County::OEIRAS => __('OEIRAS'),
            County::SINTRA => __('SINTRA'),
            County::SOBRAL_DE_MONTE_AGRACO => __('SOBRAL DE MONTE AGRAÇO'),
            County::TORRES_VEDRAS => __('TORRES VEDRAS'),
            County::VILA_FRANCA_DE_XIRA => __('VILA FRANCA DE XIRA'),
            County::AMADORA => __('AMADORA'),
            County::ODIVELAS => __('ODIVELAS'),
            County::ALTER_DO_CHAO => __('ALTER DO CHÃO'),
            County::ARRONCHES => __('ARRONCHES'),
            County::AVIS => __('AVIS'),
            County::CAMPO_MAIOR => __('CAMPO MAIOR'),
            County::CASTELO_DE_VIDE => __('CASTELO DE VIDE'),
            County::CRATO => __('CRATO'),
            County::ELVAS => __('ELVAS'),
            County::FRONTEIRA => __('FRONTEIRA'),
            County::GAVIAO => __('GAVIÃO'),
            County::MARVAO => __('MARVÃO'),
            County::MONFORTE => __('MONFORTE'),
            County::NISA => __('NISA'),
            County::PONTE_DE_SOR => __('PONTE DE SOR'),
            County::PORTALEGRE => __('PORTALEGRE'),
            County::SOUSEL => __('SOUSEL'),
            County::AMARANTE => __('AMARANTE'),
            County::BAIAO => __('BAIÃO'),
            County::FELGUEIRAS => __('FELGUEIRAS'),
            County::GONDOMAR => __('GONDOMAR'),
            County::LOUSADA => __('LOUSADA'),
            County::MAIA => __('MAIA'),
            County::MARCO_DE_CANAVESES => __('MARCO DE CANAVESES'),
            County::MATOSINHOS => __('MATOSINHOS'),
            County::PACOS_DE_FERREIRA => __('PAÇOS DE FERREIRA'),
            County::PAREDES => __('PAREDES'),
            County::PENAFIEL => __('PENAFIEL'),
            County::PORTO => __('PORTO'),
            County::POVOA_DE_VARZIM => __('PÓVOA DE VARZIM'),
            County::SANTO_TIRSO => __('SANTO TIRSO'),
            County::VALONGO => __('VALONGO'),
            County::VILA_DO_CONDE => __('VILA DO CONDE'),
            County::VILA_NOVA_DE_GAIA => __('VILA NOVA DE GAIA'),
            County::TROFA => __('TROFA'),
            County::ABRANTES => __('ABRANTES'),
            County::ALCANENA => __('ALCANENA'),
            County::ALMEIRIM => __('ALMEIRIM'),
            County::ALPIARCA => __('ALPIARÇA'),
            County::BENAVENTE => __('BENAVENTE'),
            County::CARTAXO => __('CARTAXO'),
            County::CHAMUSCA => __('CHAMUSCA'),
            County::CONSTANCIA => __('CONSTÂNCIA'),
            County::CORUCHE => __('CORUCHE'),
            County::ENTRONCAMENTO => __('ENTRONCAMENTO'),
            County::FERREIRA_DO_ZEZERE => __('FERREIRA DO ZÊZERE'),
            County::GOLEGA => __('GOLEGÃ'),
            County::MACAO => __('MAÇÃO'),
            County::RIO_MAIOR => __('RIO MAIOR'),
            County::SALVATERRA_DE_MAGOS => __('SALVATERRA DE MAGOS'),
            County::SANTAREM => __('SANTARÉM'),
            County::SARDOAL => __('SARDOAL'),
            County::TOMAR => __('TOMAR'),
            County::TORRES_NOVAS => __('TORRES NOVAS'),
            County::VILA_NOVA_DA_BARQUINHA => __('VILA NOVA DA BARQUINHA'),
            County::OUREM => __('OURÉM'),
            County::ALCACER_DO_SAL => __('ALCÁCER DO SAL'),
            County::ALCOCHETE => __('ALCOCHETE'),
            County::ALMADA => __('ALMADA'),
            County::BARREIRO => __('BARREIRO'),
            County::GRANDOLA => __('GRÂNDOLA'),
            County::MOITA => __('MOITA'),
            County::MONTIJO => __('MONTIJO'),
            County::PALMELA => __('PALMELA'),
            County::SANTIAGO_DO_CACEM => __('SANTIAGO DO CACÉM'),
            County::SEIXAL => __('SEIXAL'),
            County::SESIMBRA => __('SESIMBRA'),
            County::SETUBAL => __('SETÚBAL'),
            County::SINES => __('SINES'),
            County::ARCOS_DE_VALDEVEZ => __('ARCOS DE VALDEVEZ'),
            County::CAMINHA => __('CAMINHA'),
            County::MELGACO => __('MELGAÇO'),
            County::MONCAO => __('MONÇÃO'),
            County::PAREDES_DE_COURA => __('PAREDES DE COURA'),
            County::PONTE_DA_BARCA => __('PONTE DA BARCA'),
            County::PONTE_DE_LIMA => __('PONTE DE LIMA'),
            County::VALENÇA => __('VALENÇA'),
            County::VIANA_DO_CASTELO => __('VIANA DO CASTELO'),
            County::VILA_NOVA_DE_CERVEIRA => __('VILA NOVA DE CERVEIRA'),
            County::ALIJO => __('ALIJÓ'),
            County::BOTICAS => __('BOTICAS'),
            County::CHAVES => __('CHAVES'),
            County::MESAO_FRIO => __('MESÃO FRIO'),
            County::MONDIM_DE_BASTO => __('MONDIM DE BASTO'),
            County::MONTALEGRE => __('MONTALEGRE'),
            County::MURÇA => __('MURÇA'),
            County::PESO_DA_REGUA => __('PESO DA RÉGUA'),
            County::RIBEIRA_DE_PENA => __('RIBEIRA DE PENA'),
            County::SABROSA => __('SABROSA'),
            County::SANTA_MARTA_DE_PENAGUIAO => __('SANTA MARTA DE PENAGUIÃO'),
            County::VALPACOS => __('VALPAÇOS'),
            County::VILA_POUCA_DE_AGUIAR => __('VILA POUCA DE AGUIAR'),
            County::VILA_REAL => __('VILA REAL'),
            County::ARMAMAR => __('ARMAMAR'),
            County::CARREGAL_DO_SAL => __('CARREGAL DO SAL'),
            County::CASTRO_DAIRE => __('CASTRO DAIRE'),
            County::CINFAES => __('CINFÃES'),
            County::LAMEGO => __('LAMEGO'),
            County::MANGUALDE => __('MANGUALDE'),
            County::MOIMENTA_DA_BEIRA => __('MOIMENTA DA BEIRA'),
            County::MORTAGUA => __('MORTÁGUA'),
            County::NELAS => __('NELAS'),
            County::OLIVEIRA_DE_FRADES => __('OLIVEIRA DE FRADES'),
            County::PENALVA_DO_CASTELO => __('PENALVA DO CASTELO'),
            County::PENEDONO => __('PENEDONO'),
            County::RESENDE => __('RESENDE'),
            County::SANTA_COMBA_DAO => __('SANTA COMBA DÃO'),
            County::SAO_JOAO_DA_PESQUEIRA => __('SÃO JOÃO DA PESQUEIRA'),
            County::SAO_PEDRO_DO_SUL => __('SÃO PEDRO DO SUL'),
            County::SATAO => __('SÁTÃO'),
            County::SERNANCELHE => __('SERNANCELHE'),
            County::TABUACO => __('TABUAÇO'),
            County::TAROUCA => __('TAROUCA'),
            County::TONDELA => __('TONDELA'),
            County::VILA_NOVA_DE_PAIVA => __('VILA NOVA DE PAIVA'),
            County::VISEU => __('VISEU'),
            County::VOUZELA => __('VOUZELA'),
            County::CALHETA => __('CALHETA'),
            County::CAMARA_DE_LOBOS => __('CÂMARA DE LOBOS'),
            County::FUNCHAL => __('FUNCHAL'),
            County::MACHICO => __('MACHICO'),
            County::PONTA_DO_SOL => __('PONTA DO SOL'),
            County::PORTO_MONIZ => __('PORTO MONIZ'),
            County::RIBEIRA_BRAVA => __('RIBEIRA BRAVA'),
            County::SANTA_CRUZ => __('SANTA CRUZ'),
            County::SANTANA => __('SANTANA'),
            County::SAO_VICENTE => __('SÃO VICENTE'),
            County::PORTO_SANTO => __('PORTO SANTO'),
            County::VILA_DO_PORTO => __('VILA DO PORTO'),
            County::LAGOA_SAO_MIGUEL => __('LAGOA'),
            County::NORDESTE => __('NORDESTE'),
            County::PONTA_DELGADA => __('PONTA DELGADA'),
            County::POVOACAO => __('POVOAÇÃO'),
            County::RIBEIRA_GRANDE => __('RIBEIRA GRANDE'),
            County::VILA_FRANCA_DO_CAMPO => __('VILA FRANCA DO CAMPO'),
            County::ANGRA_DO_HEROISMO => __('ANGRA DO HEROÍSMO'),
            County::VILA_DA_PRAIA_DA_VITORIA => __('VILA DA PRAIA DA VITÓRIA'),
            County::SANTA_CRUZ_DA_GRACIOSA => __('SANTA CRUZ DA GRACIOSA'),
            County::CALHETA_SAO_JORGE => __('CALHETA'),
            County::VELAS => __('VELAS'),
            County::LAJES_DO_PICO => __('LAJES DO PICO'),
            County::MADALENA => __('MADALENA'),
            County::SAO_ROQUE_DO_PICO => __('SÃO ROQUE DO PICO'),
            County::HORTA => __('HORTA'),
            County::LAJES_DAS_FLORES => __('LAJES DAS FLORES'),
            County::SANTA_CRUZ_DAS_FLORES => __('SANTA CRUZ DAS FLORES'),
            County::CORVO => __('CORVO'),
        };
    }

    /**
     * Get the Continent of a County
     */
    public function continent(): Continent
    {
        $continentId = substr($this->value, 0, 1);

        return Continent::from($continentId);
    }

    /**
     * Get the Country of a County
     */
    public function country(): Country
    {
        $continentId = substr($this->value, 0, 4);

        return Country::from($continentId);
    }

    /**
     * Get the District of a County
     */
    public function district(): District
    {
        $continentId = substr($this->value, 0, 7);

        return District::from($continentId);
    }
}
