<?php

namespace Tests\Feature\Http\Controllers\Central;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Central\RegisterTenantController
 */
class RegisterTenantControllerTest extends TestCase
{
    /**
     * @test
     */
    public function submit_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('central.tenants.register.submit'), [
            // TODO: send request data
        ]);

        $response->assertRedirect($tenant->impersonationUrl(1));

        // TODO: perform additional assertions
    }

    // test cases...
}
