<?php

namespace Tests\Feature\Http\Controllers\Tenant\Auth;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Tenant\Auth\ForgotPasswordController
 */
class ForgotPasswordControllerTest extends TestCase
{
    /**
     * @test
     */
    public function show_link_request_form_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('tenant.password.request'));

        $response->assertOk();
        $response->assertViewIs('tenant.auth.passwords.email');

        // TODO: perform additional assertions
    }

    // test cases...
}
