<?php

namespace Tests\Feature\Http\Controllers\Tenant\Auth;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Tenant\Auth\LoginController
 */
class LoginControllerTest extends TestCase
{
    /**
     * @test
     */
    public function login_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('tenant.'), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function show_login_form_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('tenant.login'));

        $response->assertOk();
        $response->assertViewIs('tenant.auth.login');

        // TODO: perform additional assertions
    }

    // test cases...
}
