<?php

namespace Tests\Feature\Http\Controllers\Tenant;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Tenant\DashboardController
 */
class DashboardControllerTest extends TestCase
{
    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('tenant.dashboard'));

        $response->assertOk();
        $response->assertViewIs('tenant.home');

        // TODO: perform additional assertions
    }

    // test cases...
}
