<?php

namespace Tests\Feature\Http\Controllers\Tenant;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Tenant\DownloadInvoiceController
 */
class DownloadInvoiceControllerTest extends TestCase
{
    /**
     * @test
     */
    public function invoke_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('tenant.invoice.download', ['id' => $id]));

        $response->assertRedirect(tenant()->findInvoice($id)->asStripeInvoice()->invoice_pdf);

        // TODO: perform additional assertions
    }

    // test cases...
}
