<?php

namespace Tests\Feature\Http\Controllers\Tenant;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Tenant\TenantAssetsController
 */
class TenantAssetsControllerTest extends TestCase
{
    /**
     * @test
     */
    public function asset_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('stancl.tenancy.asset'));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function private_assets_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('tenant.asset'));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
